### ISSUE TITLE
[Port Request] Please port this to BetterDiscord.

### ISSUE THREAD

**Issue by Derpitron** [Tharki-God/ReMessageLogger#1]
The normal message logger (Lighty's) does not work anymore, due to being unmaintained. 

If you are willing to port and maintain this plugin for BetterDiscord, please do so. If not, then let me know if there are any working alternatives for BetterDiscord.

**Comment by yofukashino** [comment]
Idk lighty's message logger works fine for me

**Comment by Derpitron** [comment]
XenoLib doesn't seem to work for me. It says "an error was encountered while trying to load this plugin."
![image](https://user-images.githubusercontent.com/46134462/222976233-88240de4-f643-495a-9eec-d561d9e8b2fe.png)


Have you had this error? If so, how did you fix it?

**Comment by yofukashino** [comment]
> XenoLib doesn't seem to work for me. It says "an error was encountered while trying to load this plugin." ![image](https://user-images.githubusercontent.com/46134462/222976233-88240de4-f643-495a-9eec-d561d9e8b2fe.png)
> 
> Have you had this error? If so, how did you fix it?
[downloads.zip](https://github.com/Tharki-God/ReMessageLogger/files/10892678/downloads.zip)
try these

**Comment by Derpitron** [comment]
Still doesn't work for me.

**Comment by yofukashino** [comment]
> Still doesn't work for me.

Works for me tho

**Comment by Derpitron** [comment]
Could you send your list of currently used plugins? Perhaps one of my other plugins is conflicting with XenoLib.

Also, do you know how to check the error/exception thrown when trying to load XenoLib? (This part:):
![image](https://user-images.githubusercontent.com/46134462/223062482-67254f22-a386-48e1-a7f5-5742ad70bec2.png)
